spring:
  datasource:
    username: root
    password: 123456a?
    url: jdbc:mysql://localhost:3306/test?&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com/gavin/app/domain