spring:
  datasource:
    username: root
    password: 123456a?
    url: jdbc:mysql://localhost:3306/test?&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  velocity:
    cache: false
    charset: UTF-8
    check-template-location: false
    content-type: text/html
    enabled: true
    prefix: /templates/
    suffix: .vm
    toolbox-config-location: /toolbox.xml


mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com/gavin/app/domain
server:
  port: 8081