/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gavin_app_jvm_jni_MyThread */

#ifndef _Included_com_gavin_app_jvm_jni_MyThread
#define _Included_com_gavin_app_jvm_jni_MyThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gavin_app_jvm_jni_MyThread
 * Method:    start0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gavin_app_jvm_jni_MyThread_start0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
