/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gavin_app_jvm_jni_JniUtil */

#ifndef _Included_com_gavin_app_jvm_jni_JniUtil
#define _Included_com_gavin_app_jvm_jni_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gavin_app_jvm_jni_JniUtil
 * Method:    sayHelloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gavin_app_jvm_jni_JniUtil_sayHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
